# Generated by Django 2.2.3 on 2019-07-13 05:01

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavThing',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(default='uncategorized', max_length=60)),
                ('ranking', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.TextField(default='[]')),
            ],
        ),
    ]
