# Generated by Django 2.2.3 on 2019-07-13 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favthing', '0002_auto_20190713_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favthing',
            name='description',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
